[packaging] Remove python dependency. Cleanup spec. JB#50718
sailfishos/sp-smaps pull request #2
Opened 2020-09-23 10:23 UTC by mlehtima

Fix some snprintf warnings.

Python3 will be still used by the libsysperf dependency which will pull in python3.

2020-09-23 11:00 UTC, saukko commented on rpm/sp-smaps.spec
>  URL:        https://github.com/mer-tools/sp-smaps
Fix also this.

2020-09-23 11:01 UTC, saukko commented
Add also %license to the %files, small comment otherwise for URL. LGTM

2020-09-23 11:01 UTC, saukko approved these changes

2020-09-23 11:13 UTC, mlehtima commented
%license is already in the %files section but unusually at the end of it. I will move to the usual place to the start of the list.

2020-09-23 15:29 UTC, okodron requested changes
Please, add `%license COPYING` to `%files` as well.

2020-09-23 15:29 UTC, okodron commented on rpm/sp-smaps.spec
>  Requires:  %{name} = %{version}-%{release}
Better to mark this sub-package as `BuildArch: noarch`

2020-09-23 15:29 UTC, okodron commented on rpm/sp-smaps.spec
>  install -m0644 README.txt %{buildroot}%{_docdir}/%{name}-%{version}
I think this can be handled with just `%doc README.txt` in `%files`.

2020-10-02 19:38 UTC, okodron approved these changes

2020-10-19 13:37 UTC, mkosola approved these changes

2020-10-31 20:39 UTC, merged